# Generated by Django 3.2 on 2021-05-23 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eshop_products', '0005_auto_20210515_1204'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='visite_count',
            field=models.IntegerField(default=0, verbose_name='تعداد بازدید'),
        ),
    ]
